rosetta_energy_type: 'centroid'
use_ss_reinforcement: True

####1ZDD####
protein_name: '1ZDD'
fasta: 'FNMQCQRRFYEALHDPNLNEEQRNAKIKSIRDDC'
secondary_structure: 'CCHHHHHHHHHHHHTTTTTHHHHHHHHHHHHHHC'

####1ROP####
#protein_name: '1ROP'
#fasta: 'MTKQEKTALNMARFIRSQTLTLLEKLNELDADEQADICESLHDHADELYRSCLARF'
#secondary_structure: 'CCHHHHHHHHHHHHHHHHHHHHHHHHHHHCCHHHHHHHHHHHHHHHHHHHHHHHHC'

#### 1AB1 ####
#protein_name: '1AB1'
#fasta: 'TTCCPSIVARSNFNVCRLPGTSEAICATYTGCIIIPGATCPGDYAN'
#secondary_structure: 'CEECCCHHHHHHHHHHHHCCCCHHHHHHHHCCEECCCCCCTTTTTC'

#### 1K43 ####
#protein_name: '1K43'
#fasta: 'RGKWTYNGITYEGR'
#secondary_structure: 'TTTEEETTEEECCC'

#### 1ACW ####
#protein_name: '1ACW'
#fasta: 'VSCEDCPEHCSTQKAQAKCDNDKCVCEPI'
#secondary_structure: 'CCCHHHHHHHHHTTTEEEEETTEEEEECC'

#### 1WQC ####
#protein_name: '1WQC'
#fasta: 'DPCYEVCLQQHGNVKECEEACKHPVE'
#secondary_structure: 'HHHHHHHHHHCCCCHHHHHHHHCCCC'

#### 2MR9 ####
#protein_name: '2MR9'
#fasta: 'GSATFPEQTIKQLMDLGFPRDAVVKALKQTNGNAEFAASLLFQS'
#secondary_structure: 'TTTTTTHHHHHHHHHHCCCHHHHHHHHHHHTTTHHHHHHHHHCC'

#### 2MTW ####
#protein_name: '2MTW'
#fasta: 'YTNQNINISQERDLQKHGFH'
#secondary_structure: 'CCCHHHHHHHHHHHHCCCCC'

#### 2P5K ####
#protein_name: '2P5K'
#fasta: 'NKGQRHIKIREIITSNEIETQDELVDMLKQDGYKVTQATVSRDIKELHLVKVPTNNGSYKYSL'
#secondary_structure: 'CHHHHHHHHHHHHHHCCCCCHHHHHHHHHHHCCCCCHHHHHHHHHHHCCEEEEETTTEEEEEC'

#### 2P81 ####
#protein_name: '2P81'
#fasta: 'AKREFNENRYLTERRRQQLSSELGLNEAQIKIWFQNKRAKIKKS'
#secondary_structure: 'CCCCCTTTTTHHHHHHHHHHHHHCCCHHHHHHHHHHHHHHCCCC'

#### 1CRN ####
#protein_name: '1CRN'
#fasta: 'TTCCPSIVARSNFNVCRLPGTPEAICATYTGCIIIPGATCPGDYAN'
#secondary_structure: 'CEECCCHHHHHHHHHHHHCCCCHHHHHHHHCCEECCCCCCTTTTTC'

#### 2KDL ####
#protein_name: '2KDL'
#fasta: 'TTYKLILNLKQAKEEAIKELVDAGTAEKYIKLIANAKTVEGVWTLKDEIKTFTVTE'
#secondary_structure: 'TTTTTCCCHHHHHHHHHHHHHHHCCCHHHHHHHHCCCCHHHHHHHHHHHHHCCCCC'

#### 2M7T ####
#protein_name: '2M7T'
#fasta: 'GCPQGRGDWAPTSCSQDSDCLAGCVCGPNGFCG'
#secondary_structure: 'CCTTTBTTBTCEECCCGGGCTTTTCEETTTEEC'

#### 1UTG ####
#protein_name: '1UTG'
#fasta: 'GICPRFAHVIENLLLGTPSSYETSLKEFEPDDTMKDAGMQMKKVLDSLPQTTRENIMKLTEKIVKSPLCM'
#secondary_structure: 'CCCHHHHHHHHHHHHCCHHHHHHHHHHCCCCHHHHHHHHHHHHHHHCCCHHHHHHHHHHHHHHHHCGGGC'

#### 1D5Q ####
#protein_name: '1D5Q'
#fasta: 'CNLARCQLSCKSLGLKGGCQGSFCTCG'
#secondary_structure: 'CCHHHHHHHHHHHCCCEEEETTEEEEC'

#### 1ENH ####
#protein_name: '1ENH'
#fasta: 'RPRTAFSSEQLARLKREFNENRYLTERRRQQLSSELGLNEAQIKIWFQNKRAKI'
#secondary_structure: 'CCCCCCCHHHHHHHHHHHHHCCCCCHHHHHHHHHHHCCCHHHHHHHHHHHHHHC'

#### 1L2Y ####
#protein_name: '1L2Y'
#fasta: 'NLYIQWLKDGGPSSGRPPPS'
#secondary_structure: 'HHHHHHHHHCGGGCCCCCCC'

#### 1Q2K ####
#protein_name: '1Q2K'
#fasta: 'AACYSSDCRVKCVAMGFSSGKCINSKCKCYK'
#secondary_structure: 'CCCCHHHHHHHHHHHCCCEEEETTTTEEEEC'

#### 2P6J ####
#protein_name: '2P6J'
#fasta: 'MKQWSENVEEKLKEFVKRHQRITQEELHQYAQRLGLNEEAIRQFFEEFEQRK'
#secondary_structure: 'CCCCCHHHHHHHHHHHHTTTCCCHHHHHHHHHHHCCCHHHHHHHHHHTTTTC'

#### 2PMR ####
#protein_name: '2PMR'
#fasta: 'CRERIEKDLELLEKNLMEMKSIKLSDDEEAVVERALNYRDDSVYYLEKGDHITSFGCITYAHGLLDSLRMLHRIIE'
#secondary_structure: 'HHHHHHHHHHHHHHHHHHTTTTCCCHHHHHHHHHHHHHHHHHHHHHHHCCHHHHHHHHHHHHHHHHHHHHHHCCCC'

#### 3V1A ####
#protein_name: '3V1A'
#fasta: 'GSGSPLAQQIKNIHSFIHQAKAAGRMDEVRTLQENLHQLMHEYFQQSD'
#secondary_structure: 'TTTTHHHHHHHHHHHHHHHHHHCTTHHHHHHHHHHHHHHHHHHHHCCC'
